# Generated by Django 4.1.7 on 2023-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_userprofile_interests_userprofile_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='../images/no-profile-picture-icon.jpg', upload_to='images'),
        ),
    ]
