# Generated by Django 4.1.7 on 2023-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='../images/no-profile-picture-icon.jpg', upload_to='images/'),
        ),
    ]
